 const githubData = {
    "login": "surajgoraicse",
    "id": 146419909,
    "node_id": "U_kgDOCLowxQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/146419909?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/surajgoraicse",
    "html_url": "https://github.com/surajgoraicse",
    "followers_url": "https://api.github.com/users/surajgoraicse/followers",
    "following_url": "https://api.github.com/users/surajgoraicse/following{/other_user}",
    "gists_url": "https://api.github.com/users/surajgoraicse/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/surajgoraicse/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/surajgoraicse/subscriptions",
    "organizations_url": "https://api.github.com/users/surajgoraicse/orgs",
    "repos_url": "https://api.github.com/users/surajgoraicse/repos",
    "events_url": "https://api.github.com/users/surajgoraicse/events{/privacy}",
    "received_events_url": "https://api.github.com/users/surajgoraicse/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "Suraj Gorai",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Hi there 👋",
    "twitter_username": "surajgoraicse",
    "public_repos": 23,
    "public_gists": 0,
    "followers": 4,
    "following": 11,
    "created_at": "2023-09-29T07:11:02Z",
    "updated_at": "2024-10-29T14:22:43Z"
}
  
module.exports = {githubData}